version: "3"
services:
  web:
    image: nginx:1.25.2-alpine3.18
    ports:
      - "8888:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./app:/app
    depends_on:
      - php
    restart: always
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "1533"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1533"
      MYSQL_DATABASE: "slim-api"
    volumes:
      - slimphp:/var/lib/mysql
    ports:
      - "3325:3306"
    restart: always
volumes:
  slimphp: {}
